package org.xtext.example.mydsl.tests

import java.util.Map
import java.util.HashMap
import java.util.List
import java.util.ArrayList
import com.google.inject.Singleton

/**
 * Central configuration for all test suites and test patterns.
 * This is the single source of truth for test definitions used by:
 * - build-and-test.sh script
 * - TestSuiteManager
 * - Maven/Tycho test execution
 * - Coverage reports
 */
@Singleton
class TestConfiguration {
    
    /**
     * Test suite definitions with their patterns and classes
     */
    static class TestSuite {
        public String name
        public String displayName
        public String description
        public List<Class<?>> testClasses
        public String mavenPattern  // Pattern for -Dtest parameter
        public List<String> tags
        
        new(String name, String displayName, String description, 
            List<Class<?>> testClasses, String mavenPattern, List<String> tags) {
            this.name = name
            this.displayName = displayName
            this.description = description
            this.testClasses = new ArrayList(testClasses)
            this.mavenPattern = mavenPattern
            this.tags = new ArrayList(tags)
        }
    }
    
    // Single source of truth for all test suites
    public static val Map<String, TestSuite> SUITES = new HashMap() => [
        put("unit", new TestSuite(
            "unit",
            "Unit Tests",
            "Fast, isolated unit tests for individual components",
            #[
                TemplateLoaderTest
            ],
            "**/TemplateLoader*Test",
            #["unit", "fast"]
        ))
        
        put("integration", new TestSuite(
            "integration",
            "Integration Tests", 
            "Tests that verify component interactions and code generation",
            #[
                GeneratorTest
            ],
            "**/Generator*Test",
            #["integration", "generator", "codegen"]
        ))
        
        put("parsing", new TestSuite(
            "parsing",
            "Parsing Tests",
            "DSL parsing and validation tests",
            #[
                MyDslParsingTest
            ],
            "**/MyDslParsing*Test",
            #["parsing", "unit", "fast"]
        ))
        
        put("smoke", new TestSuite(
            "smoke",
            "Smoke Tests",
            "Quick smoke tests to verify basic functionality",
            #[
                MyDslParsingTest
            ],
            "**/MyDslParsing*Test",
            #["smoke", "fast"]
        ))
        
        put("all", new TestSuite(
            "all",
            "All Tests",
            "Complete test suite including all test categories",
            #[
                GeneratorTest,
                TemplateLoaderTest,
                MyDslParsingTest
            ],
            "**/*Test,**/*Tests,**/Test*",
            #[]
        ))
        
        put("fast", new TestSuite(
            "fast",
            "Fast Tests",
            "Quick-running tests for rapid feedback",
            #[
                TemplateLoaderTest,
                MyDslParsingTest
            ],
            "**/TemplateLoader*Test,**/MyDslParsing*Test",
            #["fast"]
        ))
    ]
    
    /**
     * Get test suite by name
     */
    def static TestSuite getSuite(String name) {
        return SUITES.get(name)
    }
    
    /**
     * Get Maven test pattern for a suite
     */
    def static String getMavenPattern(String suiteName) {
        val suite = SUITES.get(suiteName)
        return if (suite !== null) suite.mavenPattern else "**/*Test,**/*Tests"
    }
    
    /**
     * Get all test classes for a suite
     */
    def static List<Class<?>> getTestClasses(String suiteName) {
        val suite = SUITES.get(suiteName)
        return if (suite !== null) new ArrayList(suite.testClasses) else new ArrayList()
    }
    
    /**
     * Export configuration as properties (for shell script)
     */
    def static void exportAsProperties() {
        println("# Test Suite Configuration")
        println("# Generated by TestConfiguration.exportAsProperties()")
        println("")
        
        for (entry : SUITES.entrySet) {
            val suite = entry.value
            println("# Suite: " + suite.displayName)
            println("TEST_SUITE_" + suite.name.toUpperCase + "_PATTERN=\"" + suite.mavenPattern + "\"")
            println("TEST_SUITE_" + suite.name.toUpperCase + "_CLASSES=\"" + 
                suite.testClasses.map[simpleName].join(",") + "\"")
            println("")
        }
    }
    
    /**
     * Main method to export configuration
     */
    def static void main(String[] args) {
        if (args.length > 0 && args.get(0) == "export") {
            exportAsProperties()
        } else {
            // Print human-readable format
            println("Test Suite Configuration")
            println("========================")
            for (entry : SUITES.entrySet) {
                val suite = entry.value
                println("")
                println("Suite: " + suite.name)
                println("  Display Name: " + suite.displayName)
                println("  Pattern: " + suite.mavenPattern)
                println("  Classes: " + suite.testClasses.map[simpleName].join(", "))
                println("  Tags: " + suite.tags.join(", "))
            }
        }
    }
}
